// GENERATED CODE - DO NOT MODIFY BY HAND
// This is generated by build_runner, but provided here for completeness.

part of 'queued_url.dart';

QueuedUrl _$QueuedUrlFromJson(Map<String, dynamic> json) => QueuedUrl(
      id: json['id'] as String,
      url: json['url'] as String,
      addedAt: DateTime.parse(json['addedAt'] as String),
      status: $enumDecodeNullable(_$QueuedUrlStatusEnumMap, json['status']) ??
          QueuedUrlStatus.pending,
      attempts: (json['attempts'] as num?)?.toInt() ?? 0,
      lastError: json['lastError'] as String?,
      lastAttemptAt: json['lastAttemptAt'] == null
          ? null
          : DateTime.parse(json['lastAttemptAt'] as String),
    );

Map<String, dynamic> _$QueuedUrlToJson(QueuedUrl instance) => <String, dynamic>{
      'id': instance.id,
      'url': instance.url,
      'addedAt': instance.addedAt.toIso8601String(),
      'status': _$QueuedUrlStatusEnumMap[instance.status]!,
      'attempts': instance.attempts,
      'lastError': instance.lastError,
      'lastAttemptAt': instance.lastAttemptAt?.toIso8601String(),
    };

const _$QueuedUrlStatusEnumMap = {
  QueuedUrlStatus.pending: 'pending',
  QueuedUrlStatus.sending: 'sending',
  QueuedUrlStatus.sent: 'sent',
  QueuedUrlStatus.failed: 'failed',
};

T? $enumDecodeNullable<T>(
  Map<T, dynamic> enumValues,
  dynamic source, {
  T? unknownValue,
}) {
  if (source == null) {
    return null;
  }
  return enumValues.entries
      .firstWhere(
        (e) => e.value == source,
        orElse: () => MapEntry(unknownValue as T, null),
      )
      .key;
}
